# SPDX-License-Identifier: AGPL-3.0-or-later
# Modified for concat-song on 2026-10-07; see FORK-NOTICE.md.
"""Isolated Git fixtures for modification accounting; no repository writes."""

import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest


SCRIPT = Path(__file__).resolve().parents[1] / "check_modification_notices.py"
SPEC = importlib.util.spec_from_file_location("modification_notices", SCRIPT)
notices = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(notices)

DAY = "2026-10-07"
NEXT_DAY = "2026-10-08"
HEADER = "// SPDX-License-Identifier: AGPL-3.0-or-later\n// SPDX-FileCopyrightText: 2026 Upstream Author\n"


class ModificationNoticesTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.git("init", "-q")
        self.git("config", "user.name", "Fixture Author")
        self.git("config", "user.email", "fixture@example.invalid")
        self.git("config", "core.autocrlf", "false")
        self.write("LICENSE", b"Fixture license; preserve these exact bytes.\n")
        self.write(".gitattributes", b"* text=auto\n")
        self.write(".gitignore", b"scratch/\n")
        self.write("engine.rs", HEADER + "pub fn upstream() {}\n")
        self.write("deleted.rs", HEADER + "pub fn removable() {}\n")
        self.git("add", ".")
        self.git("-c", "commit.gpgsign=false", "commit", "-qm", "Upstream fixture")
        self.base = self.git("rev-parse", "HEAD").strip().decode()
        self.repo = notices.Repository(self.root, self.base)

    def git(self, *args):
        return subprocess.check_output(["git", "-c", f"safe.directory={self.root.as_posix()}", *args],
                                       cwd=self.root, stderr=subprocess.PIPE)

    def write(self, path, content):
        target = self.root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content.encode() if isinstance(content, str) else content)

    def modified(self, body="pub fn fork() {}\n", day=DAY):
        return HEADER + "// " + notices.NOTICE.format(day=day) + "\n" + body

    def record(self, day=DAY, summary="Fixture change"):
        notices.record(self.repo, day, summary)
        return json.loads((self.root / notices.INDEX).read_text())

    def errors(self):
        return "\n".join(notices.check(self.repo))

    def test_added_modified_deleted_and_generated_binary_entries(self):
        self.write("engine.rs", self.modified())
        self.write("added.py", "# " + notices.NOTICE.format(day=DAY) + "\nprint('fixture')\n")
        self.write("Cargo.lock", "# This file is automatically @generated by Cargo.\nversion = 4\n")
        self.write("asset.bin", b"\x00\x01\xff")
        (self.root / "deleted.rs").unlink()
        data = self.record()
        self.assertEqual("", self.errors())
        entries = data["entries"]
        self.assertEqual("modified", entries["engine.rs"]["change"])
        self.assertEqual("added", entries["added.py"]["change"])
        self.assertEqual("deleted", entries["deleted.rs"]["change"])
        self.assertIsNone(entries["deleted.rs"]["git_blob"])
        self.assertEqual("central:generated", entries["Cargo.lock"]["notice"])
        self.assertEqual("central:binary", entries["asset.bin"]["notice"])
        self.assertEqual(DAY, entries["deleted.rs"]["changed_on"])

    def test_changed_content_requires_rerecord_and_preserves_unchanged_entries(self):
        self.write("engine.rs", self.modified())
        self.write("notes.md", "First description\n")
        first = self.record()
        self.write("engine.rs", self.modified("pub fn newer() {}\n", NEXT_DAY))
        self.assertIn("engine.rs: stale git_blob", self.errors())
        second = self.record(NEXT_DAY, "Second change")
        self.assertEqual("", self.errors())
        self.assertEqual(NEXT_DAY, second["entries"]["engine.rs"]["changed_on"])
        self.assertEqual(first["entries"]["notes.md"], second["entries"]["notes.md"])

    def test_unrecorded_added_and_deleted_files_fail(self):
        self.record()
        self.write("new.json", "{}\n")
        (self.root / "deleted.rs").unlink()
        errors = self.errors()
        self.assertIn("new.json: unrecorded", errors)
        self.assertIn("deleted.rs: unrecorded", errors)

    def test_reverted_path_is_stale_and_record_removes_it(self):
        self.write("engine.rs", self.modified())
        self.record()
        self.write("engine.rs", HEADER + "pub fn upstream() {}\n")
        self.assertIn("engine.rs: stale entry", self.errors())
        self.assertNotIn("engine.rs", self.record()["entries"])
        self.assertEqual("", self.errors())

    def test_missing_invalid_date_and_tampered_self_hash_fail(self):
        data = self.record()
        data["entries"][notices.INDEX]["changed_on"] = "2026-02-30"
        self.write(notices.INDEX, notices.canonical(data))
        self.assertIn("invalid changed_on date", self.errors())
        data["entries"][notices.INDEX]["changed_on"] = DAY
        data["entries"][notices.INDEX]["summary"] = "Changed without recording"
        self.write(notices.INDEX, notices.canonical(data))
        self.assertIn("stale canonical self-fingerprint", self.errors())
        del data["entries"][notices.INDEX]["changed_on"]
        self.write(notices.INDEX, notices.canonical(data))
        self.assertIn("missing or invalid changed_on", self.errors())

    def test_rerecord_dates_an_explicit_index_metadata_edit(self):
        data = self.record()
        data["entries"][notices.INDEX]["summary"] = "Manual description update"
        self.write(notices.INDEX, notices.canonical(data))
        updated = self.record(NEXT_DAY)
        self.assertEqual(NEXT_DAY, updated["recorded_on"])
        self.assertEqual(NEXT_DAY, updated["entries"][notices.INDEX]["changed_on"])
        self.assertEqual("", self.errors())

    def test_missing_or_old_inline_date_refuses_to_write(self):
        self.write("engine.rs", HEADER + "pub fn changed() {}\n")
        with self.assertRaisesRegex(notices.NoticeError, "add a valid comment"):
            self.record()
        self.assertFalse((self.root / notices.INDEX).exists())
        self.write("engine.rs", self.modified(day=DAY))
        with self.assertRaisesRegex(notices.NoticeError, NEXT_DAY):
            self.record(NEXT_DAY)

    def test_descriptive_dated_fork_comment_is_accepted(self):
        self.write("engine.rs", HEADER + f"// Modified by the concat-song fork on {DAY}: keep the headless engine.\n")
        self.record()
        self.assertEqual("", self.errors())

    def test_preserved_headers_succeed_and_removed_copyright_or_spdx_fail(self):
        self.write("engine.rs", self.modified())
        self.record()
        self.assertIn(HEADER, (self.root / "engine.rs").read_text())
        for line in HEADER.splitlines(keepends=True):
            self.write("engine.rs", self.modified().replace(line, ""))
            with self.assertRaisesRegex(notices.NoticeError, "SPDX/copyright line removed"):
                self.record()

    def test_copyright_prose_and_fenced_examples_are_not_file_notices(self):
        text = "Copyright 2026 Actual Author\nThis paragraph discusses copyright.\n"
        text += "```rust\n" + HEADER + "```\n"
        self.assertEqual({"Copyright 2026 Actual Author"}, notices.legal_header_lines(text))

    def test_license_must_remain_byte_identical(self):
        self.write("LICENSE", "Changed license text\n")
        with self.assertRaisesRegex(notices.NoticeError, "byte-identical"):
            self.record()
        self.write("LICENSE", b"Fixture license; preserve these exact bytes.\r\n")
        self.record()
        self.assertEqual("", self.errors())

    def test_unmodified_relocated_source_uses_central_notice(self):
        (self.root / "deleted.rs").rename(self.root / "relocated.rs")
        data = self.record()
        self.assertEqual("central:unmodified-upstream-copy", data["entries"]["relocated.rs"]["notice"])
        self.assertEqual("", self.errors())

    def test_record_is_idempotent_and_checkout_line_endings_are_stable(self):
        self.write("engine.rs", self.modified())
        self.record()
        first = (self.root / notices.INDEX).read_bytes()
        self.record(NEXT_DAY, "This should not change an unchanged entry")
        self.assertEqual(first, (self.root / notices.INDEX).read_bytes())
        self.write("engine.rs", self.modified().replace("\n", "\r\n"))
        self.assertEqual("", self.errors())

    def test_staged_and_unstaged_changes_and_rename_are_accounted(self):
        self.write("engine.rs", self.modified())
        self.git("add", "engine.rs")
        self.write("engine.rs", self.modified("pub fn unstaged() {}\n"))
        (self.root / "deleted.rs").rename(self.root / "renamed.rs")
        self.write("renamed.rs", self.modified("pub fn removable() {}\n"))
        data = self.record()
        self.assertEqual("", self.errors())
        self.assertEqual("deleted", data["entries"]["deleted.rs"]["change"])
        self.assertEqual("added", data["entries"]["renamed.rs"]["change"])

    def test_ignored_untracked_scratch_is_not_recorded(self):
        self.write("scratch/private.txt", "not distribution input")
        data = self.record()
        self.assertNotIn("scratch/private.txt", data["entries"])

    def test_missing_base_fails_loudly(self):
        self.repo.base = "1" * 40
        with self.assertRaises(notices.NoticeError):
            self.record()

    @unittest.skipIf(os.name == "nt", "Windows symlink creation requires host-specific privileges")
    def test_symlink_content_is_target_text_not_target_file(self):
        (self.root / "reference.py").symlink_to("../outside-repository-secret")
        data = self.record()
        self.assertEqual("central:symlink", data["entries"]["reference.py"]["notice"])
        self.assertEqual("", self.errors())


if __name__ == "__main__":
    unittest.main()
